# Generated by Django 3.2.8 on 2021-11-11 11:52

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20211109_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='hash',
            field=models.CharField(blank=True, default=uploader.models._hash, max_length=255),
        ),
    ]
