# Generated by Django 3.2.8 on 2021-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0004_alter_uploadedfile_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Started at"
            ),
        ),
    ]
