# Generated by Django 3.2.16 on 2023-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20221108_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='stitch_count',
            field=models.IntegerField(default=0, verbose_name='Stitch count'),
        ),
    ]
