# Generated by Django 3.2.16 on 2023-12-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_uploadedfile_stitch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_microscopy',
            field=models.BooleanField(default=False),
        ),
    ]
