# Generated by Django 3.2.20 on 2023-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_uploadedfile_is_microscopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmapimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
