# Generated by Django 3.2.20 on 2023-12-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_bitmapimage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='is_microscopy',
            new_name='is_microsurgery',
        ),
    ]
