# Generated by Django 3.2.23 on 2024-01-06 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_mediafileannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='review_assigned_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Assigned at'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='review_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_assigned_to', to='uploader.owner'),
        ),
    ]
