# Generated by Django 3.2.23 on 2024-01-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_auto_20240106_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='review_assigned_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Assigned at'),
        ),
    ]
