# Generated by Django 3.2.23 on 2024-01-07 07:39

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_alter_uploadedfile_review_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='review_edit_hash',
            field=models.CharField(blank=True, default=uploader.models._hash, max_length=255),
        ),
    ]
