# Generated by Django 3.2.23 on 2024-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0021_auto_20240306_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafileannotation',
            name='annotation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
