# Generated by Django 3.2.23 on 2024-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0022_alter_mediafileannotation_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
