# Generated by Django 3.2.23 on 2025-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0025_collection_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='stitch_count',
            field=models.IntegerField(blank=True, help_text='Number of stitches in the video. Set to 0 if not applicable.', null=True, verbose_name='Stitch count'),
        ),
    ]
