# Generated by Django 3.2.23 on 2025-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0026_alter_uploadedfile_stitch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='stitch_count',
            field=models.IntegerField(help_text='Number of stitches in the video. Set to 0 if not applicable.', null=True, verbose_name='Stitch count'),
        ),
    ]
