# Generated by Django 3.2.23 on 2025-05-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0027_auto_20250415_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='data_row',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
