# Generated by Django 4.2.23 on 2025-07-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0028_uploadedfile_data_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='started_at',
            new_name='enqueued_at',
        ),
    ]
