# Generated by Django 4.2.23 on 2025-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0029_rename_started_at_uploadedfile_enqueued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enqueued at'),
        ),
    ]
