# Generated by Django 4.2.23 on 2025-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0030_alter_uploadedfile_enqueued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
    ]
