# Generated by Django 4.2.23 on 2025-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0031_uploadedfile_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Email sent at'),
        ),
    ]
